<style type="text/css">
#plupload_files input[type="file"] {
    font-size: 200px !important;
}
</style>
<script type="text/javascript">
    var LIBRETIME_PLUPLOAD_MAX_FILE_SIZE = "<?php echo $this->uploadMaxSize; ?>";
    function addurlyoutube()
      {
      divform=document.getElementById("divdownyoutubeform");
      diviframe=document.getElementById("divdownyoutube");
      iframeyt=document.getElementById("framedownyoutube");
      inputurlyt=document.getElementById("youtubeurladd");
      if(inputurlyt.value=="") 
        {
        alert("Veuillez indiquer une url youtube");
        return false;
        }
      urlyt=inputurlyt.value;
      //inputurlyt.value="";
      divform.style.display="non";
      iframeyt.src="YT.php?url="+urlyt;
      diviframe.style.display="block";
      }
    function addurlyoutubetermine()
      {
      divform=document.getElementById("divdownyoutubeform");
      diviframe=document.getElementById("divdownyoutube");
      iframeyt=document.getElementById("framedownyoutube");
      inputurlyt=document.getElementById("youtubeurladd");
      if(iframeyt.src!="") alert('Terminé');
      inputurlyt.value="";
      divform.style.display="block";
      diviframe.style.display="none";      
      //iframeyt.src="https://server.presta42.com/YT.php?url="+urlyt;
      }
</script>
<div id="upload_form" class="lib-content ui-widget ui-widget-content block-shadow padded content-pane wide-panel<?php if ($this->quotaLimitReached) { ?> hidden <?php } ?>">
    <?php
    $partitions = Application_Model_Systemstatus::GetDiskInfo();
    $status = new StdClass;
    $disk = $partitions[0];
    $used = $disk->totalSpace-$disk->totalFreeSpace;
    $total = $disk->totalSpace;
    ?>
    <div id="upload_wrapper">
        <H2>Upload Youtube Url</H2>
        <div style="display:block" id=divdownyoutubeform >
          Url : <input type="text" value="" id=youtubeurladd style="width:380px" >
          <button onclick="addurlyoutube();" >Ajouter</button>
        </div>
        <div style="display:none" id=divdownyoutube ><iframe id=framedownyoutube url="" onload="addurlyoutubetermine();" scrolling="no" style="background: white; width: 100%; height: 124px;" ></iframe></div>
        <H2>Upload Audio Files</H2>
        <form action="/rest/media" method="post" id="add-media-dropzone" class="dropzone dz-clickable">
            <?php echo $this->form->getElement('csrf') ?>
            <div class="dz-message">
                <?php echo _("Drop files here or click to browse your computer.") ?>
            </div>
        </form>
        <!--
        <div id="filelist">Your browser doesn't have Flash, Silverlight or HTML5 support.</div>
        <br />
         
        <div id="container">
                <a id="pickfiles" href="javascript:;">[Select files]</a>
                <a id="uploadfiles" href="javascript:;">[Upload files]</a>
        </div>
        -->
        <div id="uploads_disk_usage">
            <div style="padding-bottom: 2px;">Storage</div>
            <div class="disk_usage_progress_bar"></div>
            <div class="disk_usage_percent_in_use"><?php echo sprintf("%01.1f%% ", $used/$total*100) .  _("in use") ?></div>
            <div class="disk_usage_used" style="width:<?php echo sprintf("%01.1f%%", min(100, $used/$total*100)) ?>;"></div>

            <div style="margin-top: 17px; font-size: 12px;"><?php echo sprintf("%01.1fGB of %01.1fGB", $used/pow(2, 30), $total/pow(2, 30)); ?></div>
        </div>
    </div>
</div>

<div id="plupload_error">
	<table></table>
</div>

<div id="recent_uploads_wrapper" class="lib-content ui-widget ui-widget-content block-shadow content-pane wide-panel">
    <div id="recent_uploads" class="outer-datatable-wrapper padded">
        <div id="recent_uploads_filter">
            <form>
                <input type="radio" name="upload_status" id="upload_status_all" checked /><label for="upload_status_all"><?php echo _("All")?></label>
                <input type="radio" name="upload_status" id="upload_status_failed" /><label for="upload_status_failed"><?php echo _("Failed")?></label>
                <input type="radio" name="upload_status" id="upload_status_pending" /><label for="upload_status_pending"><?php echo _("Pending")?></label>
            </form>        
        </div>
        <H2><?php echo _("Recent Uploads")?></H2>
        <table id="recent_uploads_table" class="datatable lib-content ui-widget ui-widget-content block-shadow"
               cellpadding="0" cellspacing="0"></table>
    </div>
    <div style="clear: both;"></div>
</div>
